# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

"""Generate dependency-manifest/pyproject.toml and its uv.lock from every project."""

from __future__ import annotations

import argparse
import difflib
import subprocess
import tomllib
from collections.abc import Sequence
from pathlib import Path

from generate_dependency_map import Project, discover_projects

MANIFEST_DIRECTORY = "dependency-manifest"
MANIFEST_NAME = "xr-ai-dependency-manifest"

_HEADER = """\
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by .github/scripts/generate_dependency_manifest.py; do not edit.
# Aggregates every Python project so the committed uv.lock records one fully
# resolved dependency set.
"""


def manifest_members(projects: Sequence[Project]) -> list[Project]:
    """Return every project except the manifest itself, in path order."""

    return sorted(
        (project for project in projects if project.relative_directory.parts[:1] != (MANIFEST_DIRECTORY,)),
        key=lambda project: project.relative_directory.as_posix(),
    )


def render_manifest(projects: Sequence[Project]) -> str:
    """Return the manifest pyproject.toml aggregating *projects*."""

    members = manifest_members(projects)
    if not members:
        raise ValueError("no projects found to aggregate")
    python_ranges = {project.requires_python for project in members}
    if len(python_ranges) != 1:
        raise ValueError(f"projects declare different requires-python ranges: {sorted(python_ranges)}")

    dependencies = []
    for project in members:
        extras = ",".join(sorted(project.optional_dependencies))
        dependencies.append(f"{project.name}[{extras}]" if extras else project.name)
    width = max(len(project.name) for project in members)
    # Every source is editable: the projects depend on each other as editable
    # paths, and mixing modes resolves to conflicting URLs.
    sources = [
        f'{project.name:<{width}} = {{ path = "../{project.relative_directory.as_posix()}", editable = true }}'
        for project in members
    ]

    lines = [
        _HEADER,
        "[project]",
        f'name = "{MANIFEST_NAME}"',
        'version = "0.0.0"',
        'description = "Repository-wide resolved dependency manifest."',
        f'requires-python = "{python_ranges.pop()}"',
        "dependencies = [",
        *(f'    "{dependency}",' for dependency in dependencies),
        "]",
        "",
        "[tool.uv]",
        "package = false",
        "",
        "[tool.uv.sources]",
        *sources,
    ]
    return "\n".join(lines) + "\n"


def lock_manifest(root: Path) -> None:
    """Resolve the manifest lock under the repository's uv configuration."""

    subprocess.run(
        ["uv", "--config-file", "uv.toml", "lock", "--project", MANIFEST_DIRECTORY],
        cwd=root,
        check=True,
    )


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate the manifest and its lock, or verify both with ``--check``."""

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the manifest or its lock does not match the pyproject files",
    )
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parents[2]
    manifest_path = root / MANIFEST_DIRECTORY / "pyproject.toml"
    lock_path = root / MANIFEST_DIRECTORY / "uv.lock"
    regenerate = "  uv run --script .github/scripts/generate_dependency_manifest.py"
    try:
        current_manifest = manifest_path.read_text(encoding="utf-8")
        expected_manifest = render_manifest(discover_projects(root))
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        print(f"dependency manifest generation failed: {error}")
        return 1

    if not args.check:
        manifest_path.write_text(expected_manifest, encoding="utf-8")
        lock_manifest(root)
        print("Updated dependency-manifest/pyproject.toml and uv.lock.")
        return 0

    if current_manifest != expected_manifest:
        print("dependency-manifest/pyproject.toml is stale. Regenerate it with:")
        print(regenerate)
        print()
        print(
            "".join(
                difflib.unified_diff(
                    current_manifest.splitlines(keepends=True),
                    expected_manifest.splitlines(keepends=True),
                    fromfile="dependency-manifest/pyproject.toml",
                    tofile="generated dependency-manifest/pyproject.toml",
                )
            )
        )
        return 1

    # `uv lock --check` misses some metadata changes in editable members, so
    # compare a fresh resolution byte for byte and leave the committed file as is.
    current_lock = lock_path.read_text(encoding="utf-8")
    try:
        lock_manifest(root)
        fresh_lock = lock_path.read_text(encoding="utf-8")
    except subprocess.CalledProcessError:
        fresh_lock = None
    finally:
        lock_path.write_text(current_lock, encoding="utf-8")
    if current_lock != fresh_lock:
        print("dependency-manifest/uv.lock is stale. Regenerate it with:")
        print(regenerate)
        return 1

    print("Generated dependency manifest and lock are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
