# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# /// script
# requires-python = ">=3.11"
# dependencies = ["packaging>=24"]
# ///

"""Generate dependency-manifest/pyproject.toml and its uv.lock from every project."""

from __future__ import annotations

import argparse
import difflib
import subprocess
import tomllib
from collections.abc import Sequence
from pathlib import Path

from generate_dependency_map import MANIFEST_DIRECTORY, Project, discover_projects
from packaging.specifiers import SpecifierSet
from packaging.version import Version

MANIFEST_NAME = "xr-ai-dependency-manifest"
# Lock output varies across uv releases, so the lock is always produced by this
# exact version, whatever `uv` is on PATH.
UV_VERSION = "0.10.7"
_PYTHON_MINORS = range(8, 20)
REGENERATE = "  uv run --script .github/scripts/generate_dependency_manifest.py"

_HEADER = """\
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by .github/scripts/generate_dependency_manifest.py; do not edit.
# Aggregates every Python project so the committed uv.lock records one fully
# resolved dependency set. Regenerated only when uv.toml changes.
"""


def manifest_members(projects: Sequence[Project]) -> list[Project]:
    """Return every project except the manifest itself, in path order."""

    return sorted(
        (project for project in projects if project.relative_directory.parts[:1] != (MANIFEST_DIRECTORY,)),
        key=lambda project: project.relative_directory.as_posix(),
    )


def common_python_range(ranges: Sequence[str]) -> str:
    """Return the contiguous run of CPython minors every range in *ranges* accepts."""

    specifiers = [SpecifierSet(item) for item in ranges]
    minors = [minor for minor in _PYTHON_MINORS if all(Version(f"3.{minor}") in specifier for specifier in specifiers)]
    if not minors:
        raise ValueError(f"projects share no supported Python version: {sorted(set(ranges))}")
    if minors != list(range(minors[0], minors[-1] + 1)):
        raise ValueError(f"projects share a non-contiguous set of Python versions: {minors}")
    return f">=3.{minors[0]},<3.{minors[-1] + 1}"


def manifest_toml(projects: Sequence[Project]) -> str:
    """Return the manifest pyproject.toml aggregating *projects*."""

    members = manifest_members(projects)
    if not members:
        raise ValueError("no projects found to aggregate")
    python_range = common_python_range([project.requires_python for project in members])

    dependencies = []
    for project in members:
        extras = ",".join(sorted(project.optional_dependencies))
        dependencies.append(f"{project.name}[{extras}]" if extras else project.name)
    # Keys are quoted because distribution names may contain dots, which TOML
    # would otherwise read as nested tables.
    keys = [f'"{project.name}"' for project in members]
    width = max(len(key) for key in keys)
    # Every source is editable: the projects depend on each other as editable
    # paths, and mixing modes resolves to conflicting URLs.
    sources = [
        f'{key:<{width}} = {{ path = "../{project.relative_directory.as_posix()}", editable = true }}'
        for key, project in zip(keys, members, strict=True)
    ]

    lines = [
        _HEADER,
        "[project]",
        f'name = "{MANIFEST_NAME}"',
        'version = "0.0.0"',
        'description = "Repository-wide resolved dependency manifest."',
        f'requires-python = "{python_range}"',
        "dependencies = [",
        *(f'    "{dependency}",' for dependency in dependencies),
        "]",
        "",
        "[tool.uv]",
        "package = false",
        "",
        "[tool.uv.sources]",
        *sources,
    ]
    return "\n".join(lines) + "\n"


def lock_manifest(root: Path) -> None:
    """Resolve the manifest lock from scratch with the pinned uv under the root uv.toml cutoff."""

    subprocess.run(
        ["uvx", f"uv@{UV_VERSION}", "--config-file", "uv.toml", "lock", "--upgrade", "--project", MANIFEST_DIRECTORY],
        cwd=root,
        check=True,
    )


def main(argv: Sequence[str] | None = None, *, root: Path | None = None) -> int:
    """Regenerate the manifest and its lock, or verify both with ``--check``."""

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the manifest or its lock is stale",
    )
    args = parser.parse_args(argv)

    if root is None:
        root = Path(__file__).resolve().parents[2]
    manifest_path = root / MANIFEST_DIRECTORY / "pyproject.toml"
    lock_path = root / MANIFEST_DIRECTORY / "uv.lock"
    try:
        current_manifest = manifest_path.read_text(encoding="utf-8")
        current_lock = lock_path.read_text(encoding="utf-8")
        expected_manifest = manifest_toml(discover_projects(root))
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        print(f"dependency manifest generation failed: {error}")
        return 1

    if not args.check:
        manifest_path.write_text(expected_manifest, encoding="utf-8")
        try:
            lock_manifest(root)
        except (OSError, subprocess.CalledProcessError) as error:
            print(f"dependency manifest lock failed: {error}")
            return 1
        if current_manifest == expected_manifest and lock_path.read_text(encoding="utf-8") == current_lock:
            print("Generated dependency manifest and lock are already current.")
        else:
            print("Updated dependency-manifest/pyproject.toml and uv.lock.")
        return 0

    if current_manifest != expected_manifest:
        print("dependency-manifest/pyproject.toml is stale. Regenerate it with:")
        print(REGENERATE)
        print()
        print(
            "".join(
                difflib.unified_diff(
                    current_manifest.splitlines(keepends=True),
                    expected_manifest.splitlines(keepends=True),
                    fromfile="dependency-manifest/pyproject.toml",
                    tofile="generated dependency-manifest/pyproject.toml",
                )
            ),
            end="",
        )
        return 1

    # `uv lock --check` does not notice changed metadata in editable members,
    # so re-resolve and compare, then put the committed file back.
    try:
        lock_manifest(root)
        fresh_lock = lock_path.read_text(encoding="utf-8")
    except (OSError, subprocess.CalledProcessError) as error:
        print(f"dependency manifest lock failed: {error}")
        return 1
    finally:
        lock_path.write_text(current_lock, encoding="utf-8")
    if current_lock != fresh_lock:
        print("dependency-manifest/uv.lock is stale. Regenerate it with:")
        print(REGENERATE)
        return 1

    print("Generated dependency manifest and lock are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
