# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Unified typed service protocols and model clients for XR AI.

Repository code talks to the typed ``*Service`` protocols. The concrete
``OpenAICompat*`` clients cover chat, embeddings, and HTTP speech;
OCR uses the Nemotron v2 protocol and Riva speech uses optional gRPC.
"""
from ._protocols import (
    Capabilities,
    ChatMessage,
    ChatResponse,
    ChatStreamEvent,
    ContentPart,
    EmbeddingService,
    ImageInput,
    ImagePart,
    LLMService,
    OCRService,
    OCRSpan,
    STTService,
    TextPart,
    ToolCall,
    ToolDef,
    TTSService,
    VideoInput,
    VideoPart,
    VLMService,
)
from ._openai_compat import (
    OpenAICompatLLM,
    OpenAICompatEmbedding,
    OpenAICompatSTT,
    OpenAICompatTTS,
    OpenAICompatVLM,
)
from ._config import (
    AdapterSpec,
    Category,
    DeploymentSpec,
    EmbeddingSpec,
    EndpointSpec,
    KIND_OPENAI_COMPAT,
    LLMSpec,
    ModelKind,
    ModelsConfig,
    OCRSpec,
    Spec,
    STTSpec,
    TTSSpec,
    VLMSpec,
    load_models_config,
    load_models_config_from_dict,
)
from ._factory import make_embedding, make_llm, make_ocr, make_stt, make_tts, make_vlm
from ._riva_grpc import RivaSTT, RivaTTS

__all__ = [
    "Capabilities",
    "ChatMessage",
    "ChatResponse",
    "ChatStreamEvent",
    "ContentPart",
    "EmbeddingService",
    "ImageInput",
    "ImagePart",
    "LLMService",
    "OCRService",
    "OCRSpan",
    "OCRSpec",
    "make_ocr",
    "STTService",
    "TextPart",
    "ToolCall",
    "ToolDef",
    "TTSService",
    "VideoInput",
    "VideoPart",
    "VLMService",
    "OpenAICompatLLM",
    "OpenAICompatEmbedding",
    "OpenAICompatSTT",
    "OpenAICompatTTS",
    "OpenAICompatVLM",
    "AdapterSpec",
    "Category",
    "DeploymentSpec",
    "EmbeddingSpec",
    "EndpointSpec",
    "KIND_OPENAI_COMPAT",
    "RivaSTT",
    "RivaTTS",
    "LLMSpec",
    "ModelKind",
    "ModelsConfig",
    "Spec",
    "STTSpec",
    "TTSSpec",
    "VLMSpec",
    "load_models_config",
    "load_models_config_from_dict",
    "make_llm",
    "make_embedding",
    "make_stt",
    "make_tts",
    "make_vlm",
]
