# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Unified service protocols and typed HTTP clients for XR AI models.

Repository code talks to the typed ``*Service`` protocols. The concrete
clients cover OpenAI-compatible endpoints and NVIDIA Speech TTS NIM.
"""
from ._protocols import (
    Capabilities,
    ChatMessage,
    ChatResponse,
    ContentPart,
    EmbeddingService,
    ImageInput,
    ImagePart,
    LLMService,
    STTService,
    StreamingTTSService,
    TextPart,
    ToolCall,
    ToolDef,
    TTSService,
    TTSAudioChunk,
    VideoInput,
    VideoPart,
    VLMService,
)
from ._nvidia_tts_nim import NvidiaTTSNIM
from ._openai_compat import (
    OpenAICompatLLM,
    OpenAICompatEmbedding,
    OpenAICompatSTT,
    OpenAICompatTTS,
    OpenAICompatVLM,
)
from ._config import (
    AdapterSpec,
    Category,
    DeploymentSpec,
    EmbeddingSpec,
    EndpointSpec,
    KIND_NVIDIA_TTS_NIM,
    KIND_OPENAI_COMPAT,
    LLMSpec,
    ModelKind,
    ModelsConfig,
    Spec,
    STTSpec,
    TTSSpec,
    VLMSpec,
    load_models_config,
    load_models_config_from_dict,
)
from ._factory import make_embedding, make_llm, make_stt, make_tts, make_vlm

__all__ = [
    "Capabilities",
    "ChatMessage",
    "ChatResponse",
    "ContentPart",
    "EmbeddingService",
    "ImageInput",
    "ImagePart",
    "LLMService",
    "STTService",
    "StreamingTTSService",
    "TextPart",
    "ToolCall",
    "ToolDef",
    "TTSService",
    "TTSAudioChunk",
    "VideoInput",
    "VideoPart",
    "VLMService",
    "OpenAICompatLLM",
    "OpenAICompatEmbedding",
    "OpenAICompatSTT",
    "OpenAICompatTTS",
    "OpenAICompatVLM",
    "NvidiaTTSNIM",
    "AdapterSpec",
    "Category",
    "DeploymentSpec",
    "EmbeddingSpec",
    "EndpointSpec",
    "KIND_NVIDIA_TTS_NIM",
    "KIND_OPENAI_COMPAT",
    "LLMSpec",
    "ModelKind",
    "ModelsConfig",
    "Spec",
    "STTSpec",
    "TTSSpec",
    "VLMSpec",
    "load_models_config",
    "load_models_config_from_dict",
    "make_llm",
    "make_embedding",
    "make_stt",
    "make_tts",
    "make_vlm",
]
